version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/schedule_db
      - SECRET_KEY=your-super-secret-key-change-this-in-production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=False
      - ENVIRONMENT=production
    depends_on:
      - db
    volumes:
      - ./app/static:/app/app/static
      - ./app/templates:/app/app/templates
    restart: unless-stopped

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=schedule_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: 